apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    description: Template for creating and deploying customised Jupyter Notebook images.
    iconClass: icon-python
    openshift.io/display-name: Jupyter Notebook Quickstart
    tags: python,jupyter
  name: notebook-quickstart
  namespace: openshift
  selfLink: /apis/template.openshift.io/v1/namespaces/openshift/templates/notebook-quickstart
objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    lookupPolicy:
      local: true
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${APPLICATION_NAME}:latest
    source:
      contextDir: ${CONTEXT_DIR}
      git:
        ref: ${GIT_REFERENCE}
        uri: ${GIT_REPOSITORY_URL}
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: ${BUILDER_IMAGE}
          namespace: openshift
      type: Source
    triggers:
    - type: ConfigChange
    - type: ImageChange
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    replicas: 1
    selector:
      app: ${APPLICATION_NAME}
      deploymentconfig: ${APPLICATION_NAME}
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: ${APPLICATION_NAME}
          deploymentconfig: ${APPLICATION_NAME}
      spec:
        nodeSelector:
          openshift.com/gpu-accelerator: true
        automountServiceAccountToken: false
        containers:
        - env:
          - name: JUPYTER_NOTEBOOK_PASSWORD
            value: ${NOTEBOOK_PASSWORD}
          - name: JUPYTER_NOTEBOOK_INTERFACE
            value: ${NOTEBOOK_INTERFACE}
          - name: CUDA_VISIBLE_DEVICES
            value: all
          - name: NVIDIA_DRIVER_CAPABILITIES
            value: "compute,utility"
          image: ${APPLICATION_NAME}:latest
          name: notebook
          ports:
          - containerPort: 8080
            protocol: TCP
          resources:
            limits:
              memory: ${NOTEBOOK_MEMORY}
          securityContext:
           allowPrivilegeEscalation: false
           capabilities:
             drop: ["ALL"]
           seLinuxOptions:
             type: nvidia_container_t
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - notebook
        from:
          kind: ImageStreamTag
          name: ${APPLICATION_NAME}:latest
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: ${APPLICATION_NAME}
      deploymentconfig: ${APPLICATION_NAME}
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    host: ""
    port:
      targetPort: 8080-tcp
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: ${APPLICATION_NAME}
      weight: 100
parameters:
- name: APPLICATION_NAME
  required: true
  value: custom-notebook
- name: NOTEBOOK_PASSWORD
  required: true
  value: password
- name: NOTEBOOK_INTERFACE
  value: classic
- name: NOTEBOOK_MEMORY
  required: true
  value: 2Gi
- name: BUILDER_IMAGE
  required: true
  value: s2i-tensorflow-notebook:3.6
- name: GIT_REPOSITORY_URL
  required: true
- name: GIT_REFERENCE
  required: true
  value: master
- name: CONTEXT_DIR
